version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.spring_rest_api
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    build:
      context: dockerfiles
      dockerfile: Dockerfile.mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
